In [1]:
# names of hurricanes
names = ['Cuba I', 'San Felipe II Okeechobee', 'Bahamas', 'Cuba II', 'CubaBrownsville',
         'Tampico', 'Labor Day', 'New England', 'Carol', 'Janet', 'Carla', 'Hattie',
         'Beulah', 'Camille', 'Edith', 'Anita', 'David', 'Allen', 'Gilbert', 'Hugo',
         'Andrew', 'Mitch', 'Isabel', 'Ivan', 'Emily', 'Katrina', 'Rita', 'Wilma',
         'Dean', 'Felix', 'Matthew', 'Irma', 'Maria', 'Michael']

# months of hurricanes
months = ['October', 'September', 'September', 'November', 'August', 'September', 'September', 'September',
          'September', 'September', 'September', 'October', 'September', 'August', 'September', 'September',
          'August', 'August', 'September', 'September', 'August', 'October', 'September', 'September', 'July',
          'August', 'September', 'October', 'August', 'September', 'October', 'September', 'September', 'October']


# years of hurricanes
years = [1924, 1928, 1932, 1932, 1933, 1933, 1935, 1938, 1953, 1955, 1961, 1961, 1967,
         1969, 1971, 1977, 1979, 1980, 1988, 1989, 1992, 1998, 2003, 2004, 2005, 2005,
         2005, 2005, 2007, 2007, 2016, 2017, 2017, 2018]

# maximum sustained winds (mph) of hurricanes
max_sustained_winds = [165, 160, 160, 175, 160, 160, 185, 160, 160, 175, 175, 160, 160,
                       175, 160, 175, 175, 190, 185, 160, 175, 180, 165, 165, 160, 175,
                       180, 185, 175, 175, 165, 180, 175, 160]

# areas affected by each hurricane
areas_affected = [['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'],
                  ['Lesser Antilles', 'The Bahamas', 'United States East Coast', 'Atlantic Canada'],
                  ['The Bahamas', 'Northeastern United States'],
                  ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'],
                  ['The Bahamas', 'Cuba', 'Florida', 'Texas', 'Tamaulipas'], ['Jamaica', 'Yucatn Peninsula'],
                  ['The Bahamas', 'Florida', 'Georgia', 'The Carolinas', 'Virginia'],
                  ['Southeastern United States', 'Northeastern United States', 'Southwestern Quebec'],
                  ['Bermuda', 'New England', 'Atlantic Canada'], ['Lesser Antilles', 'Central America'],
                  ['Texas', 'Louisiana', 'Midwestern United States'], ['Central America'],
                  ['The Caribbean', 'Mexico', 'Texas'], ['Cuba', 'United States Gulf Coast'],
                  ['The Caribbean', 'Central America', 'Mexico', 'United States Gulf Coast'],
                  ['Mexico'], ['The Caribbean', 'United States East coast'],
                  ['The Caribbean', 'Yucatn Peninsula', 'Mexico', 'South Texas'],
                  ['Jamaica', 'Venezuela', 'Central America', 'Hispaniola', 'Mexico'], 
                  ['The Caribbean', 'United States East Coast'], ['The Bahamas', 'Florida', 'United States Gulf Coast'],
                  ['Central America', 'Yucatn Peninsula', 'South Florida'],
                  ['Greater Antilles', 'Bahamas', 'Eastern United States', 'Ontario'],
                  ['The Caribbean', 'Venezuela', 'United States Gulf Coast'], 
                  ['Windward Islands', 'Jamaica', 'Mexico', 'Texas'], ['Bahamas', 'United States Gulf Coast'],
                  ['Cuba', 'United States Gulf Coast'], ['Greater Antilles', 'Central America', 'Florida'],
                  ['The Caribbean', 'Central America'], ['Nicaragua', 'Honduras'],
                  ['Antilles', 'Venezuela', 'Colombia', 'United States East Coast', 'Atlantic Canada'], 
                  ['Cape Verde', 'The Caribbean', 'British Virgin Islands', 'U.S. Virgin Islands', 'Cuba', 'Florida'],
                  ['Lesser Antilles', 'Virgin Islands', 'Puerto Rico', 'Dominican Republic', 'Turks and Caicos Islands'],
                  ['Central America', 'United States Gulf Coast (especially Florida Panhandle)']]

# damages (USD($)) of hurricanes
damages = ['Damages not recorded', '100M', 'Damages not recorded', '40M', '27.9M', '5M', 'Damages not recorded', '306M',
           '2M', '65.8M', '326M', '60.3M', '208M', '1.42B', '25.4M', 'Damages not recorded', '1.54B', '1.24B', '7.1B',
           '10B', '26.5B', '6.2B', '5.37B', '23.3B', '1.01B', '125B', '12B', '29.4B', '1.76B', '720M', '15.1B', '64.8B',
           '91.6B', '25.1B']

# deaths for each hurricane
deaths = [90,4000,16,3103,179,184,408,682,5,1023,43,319,688,259,37,11,2068,269,318,107,65,19325,51,124,17,1836,125,87,45,
          133,603,138,3057,74]

# Update Recorded Damages
conversion = {"M": 1000000, "B": 1000000000}

### 1. Write a function that returns a new list of updated damages where the recorded data is converted to float values and the missing data is retained as "Damages not recorded".

In [2]:
def string_to_float(list_of_strings):
    "Convert a list of strings to floats. String elements are preserved."
    damages_updated = []
    
    for string in list_of_strings:
        if "B" in string:
            num = float(string[:-1]) * conversion["B"]
            damages_updated.append(float(num))
        elif "M" in string:
            num = float(string[:-1]) * conversion["M"]
            damages_updated.append(float(num))
        else:
            damages_updated.append(string)
    return damages_updated


damages_updated = string_to_float(damages)
print(damages_updated)

['Damages not recorded', 100000000.0, 'Damages not recorded', 40000000.0, 27900000.0, 5000000.0, 'Damages not recorded', 306000000.0, 2000000.0, 65800000.0, 326000000.0, 60300000.0, 208000000.0, 1420000000.0, 25400000.0, 'Damages not recorded', 1540000000.0, 1240000000.0, 7100000000.0, 10000000000.0, 26500000000.0, 6200000000.0, 5370000000.0, 23300000000.0, 1010000000.0, 125000000000.0, 12000000000.0, 29400000000.0, 1760000000.0, 720000000.0, 15100000000.0, 64800000000.0, 91600000000.0, 25100000000.0]


### 2. Write a function that constructs a dictionary made out of the lists, where the keys of the dictionary are the names of the hurricanes, and the values are dictionaries themselves containing a key for each piece of data :
`(Name, Month, Year,Max Sustained Wind, Areas Affected, Damage, Death)` 

### Thus the key "Cuba I" would have the value: 
`{'Name': 'Cuba I', 'Month': 'October', 'Year': 1924, 'Max Sustained Wind': 165, 'Areas Affected': ['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], 'Damage': 'Damages not recorded', 'Deaths': 90}.`.

In [3]:
def lists_to_dict(names, months, years, max_winds, areas_affected, damanges, deaths):
    """Combine the lists into one dictionary setting area name as the key."""
    hurricanes = {}

   
    for i in range(len(names)):
        hurricanes[names[i]] = {'Name': names[i],
                            'Month': months[i],
                            'Year': years[i],
                            'Max Sustained Wind': max_sustained_winds[i],
                            'Areas Affected': areas_affected[i],
                            'Damage': damages_updated[i],
                            'Deaths': deaths[i],
                           }
    return hurricanes

hurricanes = lists_to_dict(names, months, years, max_sustained_winds,
                           areas_affected, damages_updated, deaths)
print(hurricanes)

{'Cuba I': {'Name': 'Cuba I', 'Month': 'October', 'Year': 1924, 'Max Sustained Wind': 165, 'Areas Affected': ['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], 'Damage': 'Damages not recorded', 'Deaths': 90}, 'San Felipe II Okeechobee': {'Name': 'San Felipe II Okeechobee', 'Month': 'September', 'Year': 1928, 'Max Sustained Wind': 160, 'Areas Affected': ['Lesser Antilles', 'The Bahamas', 'United States East Coast', 'Atlantic Canada'], 'Damage': 100000000.0, 'Deaths': 4000}, 'Bahamas': {'Name': 'Bahamas', 'Month': 'September', 'Year': 1932, 'Max Sustained Wind': 160, 'Areas Affected': ['The Bahamas', 'Northeastern United States'], 'Damage': 'Damages not recorded', 'Deaths': 16}, 'Cuba II': {'Name': 'Cuba II', 'Month': 'November', 'Year': 1932, 'Max Sustained Wind': 175, 'Areas Affected': ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], 'Damage': 40000000.0, 'Deaths': 3103}, 'CubaBrownsville': {'Name': 'CubaBrownsville', 'Month': 'August', 

### 3. Write a function that converts the current dictionary of hurricanes to a new dictionary, where the keys are years and the values are lists containing a dictionary for each hurricane that occurred in that year.

### For example, the key 1932 would yield the value:
`[{'Name': 'Bahamas', 'Month': 'September', 'Year': 1932, 'Max Sustained Wind': 160, 'Areas Affected': ['The Bahamas', 'Northeastern United States'], 'Damage': 'Damages not recorded', 'Deaths': 16}, {'Name': 'Cuba II', 'Month': 'November', 'Year': 1932, 'Max Sustained Wind': 175, 'Areas Affected': ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], 'Damage': 40000000.0, 'Deaths': 3103}]`.

In [4]:
def lists_to_dict_year(names, months, years, max_winds, areas_affected, damanges, deaths):
    """Combine the lists into one dictionary setting area name as the key."""
    hurricanes = {}

   
    for i in range(len(names)):
        if years[i] not in hurricanes:
            hurricanes[years[i]] = {'Name': names[i],
                                'Month': months[i],
                                'Year': years[i],
                                'Max Sustained Wind': max_sustained_winds[i],
                                'Areas Affected': areas_affected[i],
                                'Damage': damages_updated[i],
                                'Deaths': deaths[i],
                               }
        else:
            # convert dict value to list value
            hurricanes[years[i]] = [hurricanes[years[i]]]
            # append new value to same key value
            hurricanes[years[i]]+=[{'Name': names[i],
                                   'Month': months[i],
                                   'Year': years[i],
                                   'Max Sustained Wind': max_sustained_winds[i],
                                   'Areas Affected': areas_affected[i],
                                   'Damage': damages_updated[i],
                                   'Deaths': deaths[i],
                                  }]
    return hurricanes

hurricanes_by_year = lists_to_dict_year(names, months, years, max_sustained_winds,
                           areas_affected, damages_updated, deaths)
print(hurricanes_by_year)

{1924: {'Name': 'Cuba I', 'Month': 'October', 'Year': 1924, 'Max Sustained Wind': 165, 'Areas Affected': ['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], 'Damage': 'Damages not recorded', 'Deaths': 90}, 1928: {'Name': 'San Felipe II Okeechobee', 'Month': 'September', 'Year': 1928, 'Max Sustained Wind': 160, 'Areas Affected': ['Lesser Antilles', 'The Bahamas', 'United States East Coast', 'Atlantic Canada'], 'Damage': 100000000.0, 'Deaths': 4000}, 1932: [{'Name': 'Bahamas', 'Month': 'September', 'Year': 1932, 'Max Sustained Wind': 160, 'Areas Affected': ['The Bahamas', 'Northeastern United States'], 'Damage': 'Damages not recorded', 'Deaths': 16}, {'Name': 'Cuba II', 'Month': 'November', 'Year': 1932, 'Max Sustained Wind': 175, 'Areas Affected': ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], 'Damage': 40000000.0, 'Deaths': 3103}], 1933: [{'Name': 'CubaBrownsville', 'Month': 'August', 'Year': 1933, 'Max Sustained Wind': 160, 'Areas Affe

### 4. Write a function that counts how often each area is listed as an affected area of a hurricane. Store and return the results in a dictionary where the keys are the affected areas and the values are counts of how many times the areas were affected.

In [5]:
def affected_areas_counter(affected_areas_list):
    affected_areas = {}
    for areas in areas_affected:
        for area in areas:
            if area not in affected_areas:
                affected_areas.update({area: 1})
        else: # area in affected_areas
            affected_areas[area] = affected_areas[area] + 1
    return affected_areas

affected_areas = affected_areas_counter(areas_affected)
print(affected_areas)

{'Central America': 4, 'Mexico': 3, 'Cuba': 1, 'Florida': 3, 'The Bahamas': 2, 'Lesser Antilles': 1, 'United States East Coast': 2, 'Atlantic Canada': 4, 'Northeastern United States': 2, 'Jamaica': 1, 'Cayman Islands': 1, 'Bermuda': 2, 'Texas': 3, 'Tamaulipas': 2, 'Yucatn Peninsula': 2, 'Georgia': 1, 'The Carolinas': 1, 'Virginia': 2, 'Southeastern United States': 1, 'Southwestern Quebec': 2, 'New England': 1, 'Louisiana': 1, 'Midwestern United States': 2, 'The Caribbean': 1, 'United States Gulf Coast': 7, 'United States East coast': 2, 'South Texas': 2, 'Venezuela': 1, 'Hispaniola': 1, 'South Florida': 2, 'Greater Antilles': 1, 'Bahamas': 1, 'Eastern United States': 1, 'Ontario': 2, 'Windward Islands': 1, 'Nicaragua': 1, 'Honduras': 2, 'Antilles': 1, 'Colombia': 1, 'Cape Verde': 1, 'British Virgin Islands': 1, 'U.S. Virgin Islands': 1, 'Virgin Islands': 1, 'Puerto Rico': 1, 'Dominican Republic': 1, 'Turks and Caicos Islands': 2, 'United States Gulf Coast (especially Florida Panhandle)

### 5. Write a function that finds the area affected by the most hurricanes, and how often it was hit.

In [6]:
def most_affected(areas_counts):
    
    affected_times = 0
    for key, value in affected_areas.items():
        for i in range(len(affected_areas)):
            if affected_times < value:
                affected_times = value
                most_affected_area = key
                
    return {most_affected_area: affected_times}

most_affected_area = most_affected(affected_areas)
print(most_affected_area)

{'United States Gulf Coast': 7}


### 6. Write a function that finds the hurricane that caused the greatest number of deaths, and how many deaths it caused.

In [7]:
def most_deaths(hurr_dict):
    """Find the hurricane that caused the most deaths."""
    deaths_num = 0
    
    for key, value in hurricanes.items():
        for i in range(len(hurricanes)):
            if hurricanes[key]["Deaths"] > deaths_num:
                deaths_num = hurricanes[key]["Deaths"]
                area = key
    return {area: deaths_num}

hurr_most_death = most_deaths(hurricanes)
print(hurr_most_death)

{'Mitch': 19325}


### 7. Write a function that rates hurricanes on a mortality scale according to the following ratings, where the key is the rating and the value is the upper bound of deaths for that rating.

```mortality_scale = {0: 0, 1: 100, 2: 500, 3: 1000, 4: 10000}```
                   
### For example, a hurricane with a 1 mortality rating would have resulted in greater than 0 but less than or equal to 100 deaths. A hurricane with a 5 mortality rating would have resulted in greater than 10000 deaths.

### Store the hurricanes in a new dictionary where the keys are mortality ratings and the values are lists containing a dictionary for each hurricane that falls into that mortality rating.

In [34]:
def mortality_rate(hurricanes):
    mortality_rating = {0: [], 1: [], 2: [], 3: [], 4: [], 5: []}
    for key, value in hurricanes.items():
            if hurricanes[key]["Deaths"] == 0:
                mortality_rating[0].append(key)
            elif (hurricanes[key]["Deaths"] > 0) and (hurricanes[key]["Deaths"] < 100):
                mortality_rating[1].append(key)
            elif (hurricanes[key]["Deaths"] >= 100) and (hurricanes[key]["Deaths"] < 500):
                mortality_rating[2].append(key)
            elif (hurricanes[key]["Deaths"] >= 500) and (hurricanes[key]["Deaths"] < 1_000):
                mortality_rating[3].append(key)
            elif (hurricanes[key]["Deaths"] >= 1_000) and (hurricanes[key]["Deaths"] < 10_000):
                mortality_rating[4].append(key)
            else: # hurricanes[key]["Deaths"] >= 10_000:
                mortality_rating[5].append(key)
    return mortality_rating

mortality_ratings = mortality_rate(hurricanes)
print(mortality_ratings)

{0: [], 1: ['Cuba I', 'Bahamas', 'Carol', 'Carla', 'Edith', 'Anita', 'Andrew', 'Isabel', 'Emily', 'Wilma', 'Dean', 'Michael'], 2: ['CubaBrownsville', 'Tampico', 'Labor Day', 'Hattie', 'Camille', 'Allen', 'Gilbert', 'Hugo', 'Ivan', 'Rita', 'Felix', 'Irma'], 3: ['New England', 'Beulah', 'Matthew'], 4: ['San Felipe II Okeechobee', 'Cuba II', 'Janet', 'David', 'Katrina', 'Maria'], 5: ['Mitch']}


### 8. Write a function that finds the hurricane that caused the greatest damage, and how costly it was.

In [45]:
def most_dmg(hurr_dict):
    damage = 0
    most_dmg = {key:hurricanes[key]["Damage"] for key, value in hurricanes.items()}
    for key, value in most_dmg.items():
        try:
            if most_dmg[key] > damage:
                most_damage_hurr = key
                damage = most_dmg[key]
        except TypeError:
            continue
    return {most_damage_hurr: damage}
    
print(most_dmg(hurricanes))

{'Katrina': 125000000000.0}


### 9. Write a function that rates hurricanes on a damage scale according to the following ratings, where the key is the rating and the value is the upper bound of damage for that rating.

`damage_scale = {0: 0, 1: 100_000_000, 2: 1_000_000_000, 3: 10_000_000_000, 4: 50_000_000_000}`

### For example, a hurricane with a 1 damage rating would have resulted in damages greater than 0 USD but less than or equal to 100000000 USD. A hurricane with a 5 damage rating would have resulted in damages greater than 50000000000 USD (talk about a lot of money).

### Store the hurricanes in a new dictionary where the keys are damage ratings and the values are lists containing a dictionary for each hurricane that falls into that damage rating.

In [48]:
def damage_scale(hurricanes):
    mortality_rating = {0: [], 1: [], 2: [], 3: [], 4: [], 5: []}
    for key, value in hurricanes.items():
        try:
            if hurricanes[key]["Damage"] == 0:
                mortality_rating[0].append(key)
            elif (hurricanes[key]["Damage"] > 0) and (hurricanes[key]["Damage"] < 100_000_000):
                mortality_rating[1].append(key)
            elif (hurricanes[key]["Damage"] >= 100_000_000) and (hurricanes[key]["Damage"] < 1_000_000_000):
                mortality_rating[2].append(key)
            elif (hurricanes[key]["Damage"] >= 1_000_000_000) and (hurricanes[key]["Damage"] < 10_000_000_000):
                mortality_rating[3].append(key)
            elif (hurricanes[key]["Damage"] >= 10_000_000_000) and (hurricanes[key]["Damage"] < 50_000_000_000):
                mortality_rating[4].append(key)
            else: # hurricanes[key]["Damage"] >= 50_000_000_000:
                mortality_rating[5].append(key)
        except TypeError:
            continue
    return mortality_rating

damage_scale_ratings = damage_scale(hurricanes)
print(damage_scale_ratings)

{0: [], 1: ['Cuba II', 'CubaBrownsville', 'Tampico', 'Carol', 'Janet', 'Hattie', 'Edith'], 2: ['San Felipe II Okeechobee', 'New England', 'Carla', 'Beulah', 'Felix'], 3: ['Camille', 'David', 'Allen', 'Gilbert', 'Mitch', 'Isabel', 'Emily', 'Dean'], 4: ['Hugo', 'Andrew', 'Ivan', 'Rita', 'Wilma', 'Matthew', 'Michael'], 5: ['Katrina', 'Irma', 'Maria']}
